### ISSUE TITLE
!agenda functionaliteit

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/PinkieBot-Perl#10]
Originally reported by: **Anonymous**

----------------------------------------

omdat iedereen altijd zeurt dat iets op de agenda moet; waarna ik het handmatig moet onthouden. Vrij irritant. Om dit te vermakkelijken wil ik een !agenda thingie in pinkiebot zodat iedereen die kan gebruiken in plaats van te wachten tot ik teken van leven vertoon

voorbeeld use:
<somepony> !agenda dit is text voor de agenda

voorbeeld resultaat:
een email met subject: somepony: dit is text voor de agenda
(lege email, of, als het toch beschikbaar is, laatste x regels van het channel voor context)

----------------------------------------
- Bitbucket: https://bitbucket.org/WaveHack/pinkiebot/issue/10

**Comment by rctgamer3** [comment]
Heeft geen toegevoegde waarde meer voor PinkieBot.
