### ISSUE TITLE
idea: ping/pong

### ISSUE THREAD

**Issue by WaveHack** [WaveHack/PinkieBot-Perl#4]
Originally reported by: **Anonymous**

----------------------------------------

The idea:
Whenever someone say the word (without any other words) "ping" 
then Pinkiebot should return with "pong" (or something else that fits pinkiebot :P ) 
that way poeple can check if their chat/internet still works.

for example
<boem777>ping
<PinkieBot>pong

----------------------------------------
- Bitbucket: https://bitbucket.org/WaveHack/pinkiebot/issue/4

**Comment by rctgamer3** [comment]
Trivial. One can just ping the IRC server.
